name: flux-dev-app
version: 0.1.0
entry: predict.py:Predictor
build:
  gpu: true
  python_version: "3.11"
  requirements_file: requirements.txt
files:
  - predict.py
  - requirements.txt
  - car.jpg      # nếu cần
